#!/bin/bash
videosize="1280x720"
videocard="/dev/video0"
audiocard="hw:CARD=MS2109,DEV=0"
framerate="30"
keyframe="60"
bitrate="2000k"
bitrateaudio="128k"
sampling="48000"
preset="ultrafast"
ingesturl="rtmp://mrs02.contribute.live-video.net/app/"
ingestkey="live_60231354_NH447CqBW5ZOmAN98Xm1ss"
streamkey="$ingesturl$ingestkey"

# -x264opts keyint=$keyframe -g $framerate -pix_fmt yuv420p \

# ffmpeg_command = ffmpeg -nostdin -re -f v4l2 -s "$resolution" -framerate $framerate -i $videocard -f alsa -ac 2 -i "$audiocard" -vcodec libx264 -framerate $framerate -rtbufsize $buffer -s $resolution -preset $preset -pix_fmt yuv420p -crf 17 -force_key_frames ‘expr:gte(t,n_forced*2)’ -minrate $buffer -maxrate $buffer -b:v $buffer -bufsize $buffer -acodec l>

# ffmpeg \
#         -f v4l2 -input_format mjpeg -framerate $framerate -s $videosize -i $videocard \
#         -f alsa -ac 2 -i $audiocard \
#         -c:v libx264 -b:v $bitrate -preset $preset -vf format=yuv420p \
#         -c:a aac -b:a $bitrateaudio \
#         -f flv -drop_pkts_on_overflow 1 -attempt_recovery 1 -recovery_wait_time 1 $streamkey
        
ffmpeg \
        -re -f v4l2 -thread_queue_size 2048 -s $videosize -input_format mjpeg -framerate $framerate -i $videocard \
        -f alsa -ac 2 -thread_queue_size 4096 -i $audiocard -c:a aac -b:a $bitrateaudio -ar $sampling \
        -vf format=yuv420p -c:v h264_v4l2m2m -b:v $bitrate -preset $preset -f flv - | ffmpeg -i - -c copy -f flv -drop_pkts_on_overflow 1 -attempt_recovery 1 -recovery_wait_time 1 $streamkey
